services:
  rfshop:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db_rfshop:
        condition: service_healthy

  db_rfshop:
    container_name: db_rfshop
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_rfshop_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_rfshop_data:
