spring:
  application:
    name: rfshop
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:file:.env[.properties]

  logging:
    level:
      org.springframework: DEBUG
      org.example.rfshop: DEBUG